class Strings{
  Strings._();
  static const String stoxplay = "Stoxplay";
  static const String login = "Log In";
  static const String email = "Email";
  static const String userName = "User Name";
  static const String dob = "DATE OF BIRTH";
  static const String verification = "Verification";
  static const String weHaveSentACodeToYourNumber = "We have sent a code to your number";
  static const String dummyMobileNumber = "xxxxxxxx25";
  static const String ddMMYYYY = "DD/MM/YYYY";
  static const String uploadPhoto = "UPLOAD PHOTO";
  static const String createYourProfile = "Create your pofile";
  static const String password = "Password";
  static const String phoneNumber = "Phone number";
  static const String mobileNumber = "Mobile number";
  static const String rememberMe = "Remember me";
  static const String code = "Code";
  static const String resendIn = "resend in ";
  static const String forgotPassword = "Forgot Password";
  static const String pleaseSignInToExistingAccount = "Please sign in to existing account";
  static const String weWillSendYouOTP = "We will send you One Time Password(OTP)";
  static const String signUp = "Sign Up";
  static const String verify = "VERIFY";
  static const String upload = "UPLOAD";
  static const String dontHaveAnAccount = "Don't have an account";
  static const String haveAnInviteCode = "Have an Invite Code?";
  static const String iCertifyThatIAmAbove18Years = "I certify that I am above 18 years";
  static const String termsAndConditions = "By continuing, you agree to our terms & conditions and privacy policies.";
  static const String sambhavatTechnologies = "@SAMBHAVAT TECHNOLOGIES PRIVATE LIMITED.";
  static const String pleaseCheckTermsAndConditions = "Please check terms and conditions";
  static const String uploadYourPhoto = "Upload your photo";
  static const String camera = "Camera";
  static const String gallery = "Gallery";
  static const String play = "Play";
  static const String learn = "Learn";
  static const String home = "Home";
  static const String wallet = "Wallet";
  static const String profile = "Profile";
  static const String monitor = "Monitor";
  static const String sectorsPlay = "Sector's Play";
  static const String indianStockMarketChampionship = "Indian Stock Market Championship";

}
